messages:
  command-help: '&cPlease, use: /npc <create|rec|play|delete> <name>.'
  npc-already-exists: '&c&lERROR! &cThis NPC already exists.'
  npc-does-not-exists: '&c&lERROR! &cThis NPC does not exists.'
  create-help: '&cPlease, use: /npc create <name> <skin (Optional|Default: Steve)>.'
  create-success: '&eNPC created Sucessfully! Name: {name}, using the skin {skin}. To record, please use /npc rec <name> <seconds>.'
  create-cancelled: '&cCreation of NPC {name} canceled.'
  rec-help: '&cPlease, use: /npc rec <name> <seconds>.'
  rec-invalid-seconds: '&c&lERROR! &cYou must insert a valid seconds value.'
  rec-starting: '&eStarting to record NPC {name} movements in 3 seconds.'
  delete-help: '&cPlease, use: /npc delete <name>.'
  delete-success: '&cNPC {name} deleted with success!'
  delete-canceled: '&cDeletion of NPC {name} canceled.'
  play-help: '&cPlease, use: /npc play <name>.'
  play-playing: '&ePlaying animation from NPC {name}.'
  recording-now: '&eRecording now!'
  recording-ended: '&cRecording ended!'
  recording-time: '&eRecording for {time} seconds!'
mysql:
  host: 'localhost'
  database: 'npc'
  port: 3306
  username: 'root'
  password: ''